# Nodes for the calibration
calibration_nodes: 

    transforms:
      arm_chessboard_link:
         transform: [0.0, 0.0,  0.0,  3.1415, 0.0, 3.1415]
      xtion_link:
         transform: xtion_link
 
    joints:
       arm_1_joint: 0.0
       arm_2_joint: 0.0
       arm_3_joint: 0.0
       arm_4_joint: 0.0
       arm_5_joint: 0.0
       arm_6_joint: 0.0
       arm_7_joint: 0.0
       head_1_joint: 0.0
       head_2_joint: 0.0


#################################

    cameras:
        
        xtion:
            topic: /xtion/rgb/image_raw
            topic_rect: /xtion/rgb/image_rect_color
            transform: xtion_link
            optical_frame: /xtion_optical_frame
            camera_info: /xtion/rgb/camera_info

    kinematic_chains:
      arm:
        root_name: head_2_link
        tip_name: arm_7_link
              
    tools:
        chessboard:
            transform: arm_chessboard_link


#####################################

calibration_edges:

     arm_chain:
       kinematic_chain: arm
       tool: chessboard
       sensors: [xtion]  
       joints:
          [[-1.55, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
           [-0.03, -0.01, 1.0, -0.14, -1.73, 1.53, -1.78, -0.29, 0.50],
           [-0.03, -0.41, 0.09, -0.21, -1.83, 1.96, 2.03, 0.13, 1.04],
           [-1.21, -0.17, 0.0, -0.40, -2.32, 0.94, -2.07, -0.29, 0.0]]
       



