play_motion:
  controllers: [arm_controller, head_controller, torso_controller]
  motions:
    home:
      joints: [torso_lift_joint, head_1_joint, head_2_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.15, 0.0, 0.0, 0.21, 0.35, 0.0, 0.0, -1.57, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.15, 0.0, 0.0, 0.21, 0.35, -0.2, 0.0, -1.57, 1.52, 0.0]
        time_from_start: 1.5
      - positions: [0.15, 0.0, 0.0, 0.21, 0.35, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 3.5
      - positions: [0.15, 0.0, 0.0, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 6.0
      - positions: [0.0, 0.0, 0.0, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 9.0
    pregrasp:
      joints: [torso_lift_joint, head_1_joint, head_2_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.35, 0.0, 0.0, 0.0, -1.12, 0.0, 2.16, -1.57, 1.52, 0.0]
        time_from_start: 0.0
      - positions: [0.35, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 11.0
      - positions: [0.35, 0.0, -0.6, 0.0, 0.2, -1.68, 1.37, -1.58, 0.74, -0.08]
        time_from_start: 17.0
      - positions: [0.35, 0.0, -0.6, 0.0, -0.07, -1.68, 1.37, -1.58, 0.74, -0.08]
        time_from_start: 21.0

    open_gripper:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.045, 0.045]
        time_from_start: 0.0

    close_gripper:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.0

    head_tour:
      joints: [head_1_joint, head_2_joint]
      points: 
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, 0]
        time_from_start: 3.0
      - positions: [0.7, 0.3]
        time_from_start: 6.0
      - positions: [0.7, -0.3]
        time_from_start: 9.0
      - positions: [0.7, 0.3]
        time_from_start: 12.0
      - positions: [-0.7, 0.3]
        time_from_start: 15.0
      - positions: [-0.7, -0.3]
        time_from_start: 18.0
      - positions: [0, 0]
        time_from_start: 21.0



