play_motion:
  controllers: [arm_controller, head_controller, torso_controller, hand_controller]
  motions:
    home:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.15, 0.21, 0.35, 0.0, 0.0, -1.57, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.15, 0.21, 0.35, -0.1, 0.0, -1.57, 1.52, 0.0]
        time_from_start: 1.5
      - positions: [0.15, 0.21, 0.35, -0.1, 1.9, -1.57, 1.52, 0.0]
        time_from_start: 3.5
      - positions: [0.15, 0.21, -1.34, -0.1, 1.9, -1.57, 1.52, 0.0]
        time_from_start: 6.0
      - positions: [0.06, 0.05, -1.34, -0.1, 1.9, -1.57, 1.52, 0.0]
        time_from_start: 9.0
      meta:
        name: Home
        usage: demo
        description: 'Go home'
    pregrasp:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.06, 0.05, -1.34, -0.1, 1.9, -1.57, 1.52, 0.0]
        time_from_start: 0.0
      - positions: [0.34, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 1.5
      - positions: [0.34, 0.21, 0.35, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 4.5
      - positions: [0.34, 0.21, 0.35, -0.2, 0.0, -1.57, 1.52, 0.0]
        time_from_start: 8.0
      - positions: [0.34, 0.21, 0.35, -3.0, 0.0, -1.57, 1.52, 0.0]
        time_from_start: 10.0
      - positions: [0.34, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
        time_from_start: 12.0
      meta:
        name: pregrasp
        usage: demo
        description: 'pregrasp'

    open_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, -1.0, -1.0]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.0]
        time_from_start: 2.5
      meta:
        name: open_hand
        usage: demo
        description: 'open_hand'

    close_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [2.37, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [6.2, 6.8, 9.2]
        time_from_start: 2.5
      meta:
        name: close_hand
        usage: demo
        description: 'close_hand'

    pointing_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [2.37, -1.0, 0.0]
        time_from_start: 0.1
      - positions: [6.2, 0.0, 9.2]
        time_from_start: 1.5
      meta:
        name: pointing_hand
        usage: demo
        description: 'pointing_hand'

    gun_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, -1.0, 0.0]
        time_from_start: 0.1
      - positions: [0.0, 0.0, 9.2]
        time_from_start: 1.5
      meta:
        name: gun_hand
        usage: demo
        description: 'gun_hand'

    thumb_up_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, 0.0, 0.0]
        time_from_start: 0.1
      - positions: [0.0, 6.8, 9.2]
        time_from_start: 1.5
      meta:
        name: thumb_up_hand
        usage: demo
        description: 'thumb_up_hand'

    # pregrasp_thumb_hand:
    #   joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
    #   points:
    #   - positions: [0.0, -1.0, -1.0]
    #     time_from_start: 0.1
    #   - positions: [3.37, 0.0, 0.0]
    #     time_from_start: 1.5
    #   meta:
    #     name: pregrasp_thumb_hand
    #     usage: demo
    #     description: 'pregrasp_thumb_hand'

    pinch_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [0.0, -1.0, -1.0]
        time_from_start: 0.1
      - positions: [3.37, 4.0, 0.0]
        time_from_start: 1.5
      meta:
        name: pinch_hand
        usage: demo
        description: 'pinch_hand'

    head_tour:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, 0]
        time_from_start: 3.0
      - positions: [0.7, 0.3]
        time_from_start: 6.0
      - positions: [0.7, -0.3]
        time_from_start: 9.0
      - positions: [0.7, 0.3]
        time_from_start: 12.0
      - positions: [-0.7, 0.3]
        time_from_start: 15.0
      - positions: [-0.7, -0.3]
        time_from_start: 18.0
      - positions: [0, 0]
        time_from_start: 21.0
      meta:
        name: head_tour
        usage: demo
        description: 'head_tour'
    wave:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint,
      arm_5_joint, arm_6_joint, arm_7_joint]
      points:
      - positions: [0.06337464909724033, -0.679638896132783, -3.1087325315620733, 2.0882339360702575, -1.1201172410014792, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 0.0
      - positions: [0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 1.0
      - positions: [0.06335930908588873, -0.7231278283145929, -2.9385504456273295, 2.2121050027803877, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 2.0
      - positions: [0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 3.0
      meta:
        name: Wave
        usage: demo
        description: 'wave'

    pregrasp_weight:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      meta:
        name: pregrasp_weight
        usage: demo
        description: 'Pregrasp weight'

    do_weights:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 2.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 4.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 6.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 8.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 10.0
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 12.0
      meta:
        name: do_weights
        usage: demo
        description: 'Do weights'
    pick_from_floor:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint,
      arm_5_joint, arm_6_joint, arm_7_joint,
      hand_thumb_joint, hand_mrl_joint, hand_index_joint]
      points:
      - positions: [0.06, 1.3398169936645752, -1.0865020172114928, 0.14015915261777295, -0.554948419882215, -1.4599426578279369, -0.713353056118629, 0.04145437279716574, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.06, 1.3398476736872784, -1.2950801515593122, 0.139530212152357, -0.5549675949699406, -1.4599426578279369, -0.7133758834164247, 0.041449807337606615, 2.7, 0.0, 0.0]
        time_from_start: 2.0
      - positions: [0.06, 1.3398476736872784, -1.2950801515593122, 0.139530212152357, -0.5549675949699406, -1.4599426578279369, -0.7133758834164247, 0.041449807337606615, 6.2, 6.8, 9.2]
        time_from_start: 4.0
      - positions: [0.06, 1.3400317538234978, -0.3915074629155225, 0.13968361226587306, -1.5707678672561871, -1.4599426578279369, -0.7133895797951022, 0.0414635037162841, 6.2, 6.8, 9.2]
        time_from_start: 6.0

    follow_by_arm_initial_pose:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'hand_thumb_joint', 'hand_index_joint', 'hand_mrl_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577, -0.001, -0.0, -0.001]
        time_from_start: 0.0
      meta:
        name: follow_by_arm_initial_pose
        usage: demo
        description: 'follow_by_arm_initial_pose'