arm_1_joint:
  type: pal_local_joint_control::DirectEffortControl
  motor_torque_constant: -0.1149
  torque_scaling_arm_4_joint: 1.0
  viscous_friction_arm_4_joint: 2.0
  static_friction_arm_4_joint: 0.5
