gains:
  torso_lift_joint: {p: 30000,  d: 250, i: 10, i_clamp: 1.5}
  head_1_joint: {p: 3000,  d: 5, i: 1, i_clamp: 1.5}
  head_2_joint: {p: 3000,  d: 5, i: 1, i_clamp: 1.5}
  xtion_frame_joint: {p: 0.5,  d: 0, i: 0, i_clamp: 1.5}

  arm_1_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 60}
  arm_2_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 50}
  arm_3_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 50}
  arm_4_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 50}
  arm_5_joint: {p: 500,  d: 1, i: 0.1, i_clamp: 3, torque_clamp: 50}
  arm_6_joint: {p: 500,  d: 1, i: 0.1, i_clamp: 3, torque_clamp: 50}
  arm_7_joint: {p: 500,  d: 1, i: 0.1, i_clamp: 3, torque_clamp: 50}

#  hand_index_joint: &finger_gains {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
#  hand_thumb_joint: *finger_gains
#  hand_mrl_joint: *finger_gains
