collision_parameters:
  ground:
    position: [0.0, 0.0, -1.05]
    rpy: [0.0, 0.0, 0.0]
  collision_blacklist:
    arm_2_link:
      - torso_lift_link
    arm_2_link_with_environment:
      - torso_lift_link
    arm_5_link:
      - wrist_ft_link
      - gripper_link
    arm_6_link:
      - wrist_ft_link
      - gripper_link
    arm_tool_link:
      - wrist_ft_link
      - gripper_link
    ground:
      - base_link
      - caster_back_left_1_link
      - caster_back_left_1_link
      - caster_back_left_2_link
      - caster_back_right_1_link
      - caster_back_right_2_link
      - caster_front_left_1_link
      - caster_front_left_2_link
      - caster_front_right_1_link
      - caster_front_right_2_link
      - wheel_right_link
      - wheel_left_link
    wrist_ft_link:
      - wrist_ft_tool_link
    # PAL and WSG Gripper links
    gripper_link:
      - gripper_tool_link
      - wrist_ft_tool_link
      - wrist_ft_link
    gripper_tool_link:
      - gripper_right_finger_link
      - gripper_left_finger_link
      - wrist_ft_tool_link
    hand_link:
    # Hey5 links
      - wrist_ft_tool_link
      - wrist_ft_link
    hand_tool_link:
      - hand_safety_box
      - hand_little_virtual_2_link
      - hand_middle_abd_link
      - hand_ring_virtual_3_link
      - hand_little_virtual_1_link
      - hand_index_flex_1_link
      - hand_index_flex_1_link
      - hand_middle_virtual_3_link
      - hand_ring_virtual_1_link
      - hand_middle_virtual_2_link
      - hand_thumb_flex_2_link
      - hand_index_abd_link
      - hand_index_flex_1_link
      - hand_index_flex_2_link
      - hand_index_flex_3_link
      - hand_index_virtual_1_link
      - hand_index_virtual_2_link
      - hand_index_virtual_3_link
      - hand_little_abd_link
      - hand_little_flex_1_link
      - hand_little_flex_2_link
      - hand_little_flex_3_link
      - hand_little_virtual_1_link
      - hand_little_virtual_2_link
      - hand_little_virtual_3_link
      - hand_middle_abd_link
      - hand_middle_flex_1_link
      - hand_middle_flex_2_link
      - hand_middle_flex_3_link
      - hand_middle_virtual_1_link
      - hand_middle_virtual_2_link
      - hand_middle_virtual_3_link
      - hand_palm_link
      - hand_ring_abd_link
      - hand_ring_flex_1_link
      - hand_ring_flex_2_link
      - hand_ring_flex_3_link
      - hand_ring_virtual_1_link
      - hand_ring_virtual_2_link
      - hand_ring_virtual_3_link
      - hand_safety_box
      - hand_thumb_abd_link
      - hand_thumb_flex_1_link
      - hand_thumb_flex_2_link
      - hand_thumb_virtual_1_link
      - hand_thumb_virtual_2_link
